### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: dreamDroid
email: support@dreamdroid.org
description: dreamDroid - Dreambox Remote and Streaming
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dreamdroid.org" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: followsre
github_username:  sreichholf
author: Stephan Reichholf
logo: assets/images/large-logo.png
twitter:
  username: followsre
social:
  name: Stephan Reichholf
  links:
    - https://twitter.com/followsre
    - https://github.com/sreichholf

languages: ["en", "de"]
ampdir: amp

github: https://github.com/sreichholf/dreamDroid

cookie_consent: true

### Build settings
markdown: kramdown

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll
  - jekyll-remote-theme

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
